language: java

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ff9227f9-2b13-4240-b18c-0e20c55a218e

addons:
  apt:
    packages:
      - sshpass

sudo: false

branches:
  only:
  - master
  - demo-1
  - backend-10
  - backend-19

before_install:
  cd backend

install:
- mvn clean install
